# [作業目標]
- 仿造範例的 One Hot Encoding, 將指定的資料進行編碼

# [作業重點]
- 將 sub_train 進行 One Hot Encoding 編碼 (In[4], Out[4])

In [19]:
import os
import numpy as np
import pandas as pd

In [20]:
# 設定 data_path, 並讀取 app_train
dir_data = './data/'
f_app_train = os.path.join(dir_data, 'application_train.csv')
app_train = pd.read_csv(f_app_train)

## 作業
將下列部分資料片段 sub_train 使用 One Hot encoding, 並觀察轉換前後的欄位數量 (使用 shape) 與欄位名稱 (使用 head) 變化

In [68]:
sub_train = pd.DataFrame(app_train['WEEKDAY_APPR_PROCESS_START'])
print(sub_train.shape)
sub_train.head()
print(sub_train.iloc[0:100,0].values)

(307511, 1)
['WEDNESDAY' 'MONDAY' 'MONDAY' 'WEDNESDAY' 'THURSDAY' 'WEDNESDAY' 'SUNDAY'
 'MONDAY' 'WEDNESDAY' 'THURSDAY' 'SATURDAY' 'FRIDAY' 'FRIDAY' 'THURSDAY'
 'MONDAY' 'SATURDAY' 'THURSDAY' 'MONDAY' 'FRIDAY' 'MONDAY' 'FRIDAY'
 'MONDAY' 'THURSDAY' 'FRIDAY' 'THURSDAY' 'SATURDAY' 'MONDAY' 'SATURDAY'
 'WEDNESDAY' 'TUESDAY' 'WEDNESDAY' 'TUESDAY' 'SATURDAY' 'THURSDAY'
 'FRIDAY' 'MONDAY' 'THURSDAY' 'FRIDAY' 'FRIDAY' 'TUESDAY' 'TUESDAY'
 'MONDAY' 'THURSDAY' 'WEDNESDAY' 'WEDNESDAY' 'MONDAY' 'MONDAY' 'WEDNESDAY'
 'THURSDAY' 'THURSDAY' 'THURSDAY' 'TUESDAY' 'TUESDAY' 'THURSDAY' 'TUESDAY'
 'MONDAY' 'MONDAY' 'WEDNESDAY' 'MONDAY' 'TUESDAY' 'MONDAY' 'TUESDAY'
 'THURSDAY' 'MONDAY' 'MONDAY' 'WEDNESDAY' 'TUESDAY' 'THURSDAY' 'SUNDAY'
 'SATURDAY' 'MONDAY' 'MONDAY' 'FRIDAY' 'WEDNESDAY' 'THURSDAY' 'FRIDAY'
 'THURSDAY' 'TUESDAY' 'TUESDAY' 'THURSDAY' 'THURSDAY' 'THURSDAY'
 'THURSDAY' 'WEDNESDAY' 'THURSDAY' 'FRIDAY' 'WEDNESDAY' 'SUNDAY' 'FRIDAY'
 'WEDNESDAY' 'TUESDAY' 'WEDNESDAY' 'WEDNESDAY' 'MONDAY' 'SUNDAY'

In [81]:
"""
Your Code Here
"""

x=sub_train
print(x.shape)
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
x = labelencoder.fit_transform(x)
print(x.shape)
print(type(x))
x = pd.DataFrame(x)
onehotencoder = OneHotEncoder(categorical_features = [0])
x = onehotencoder.fit_transform(x).toarray()
#X = pd.get_dummies(sub_train)
print(x)

(307511, 1)
(307511,)
<class 'numpy.ndarray'>
[[0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]]


/Users/Alanhuang/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:125: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
